### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rossjones** [opendatamonitor/socrata-harvester#3]
Would it be possible to get some documentation for setup?  A Socrata harvester obviously has wider use, but at the moment is dependant on Mongo which doesn't come as part of the main CKAN installation.

Would be useful to know how it is used, and perhaps how this extension could be used without mongo.

**Comment by vkaff** [comment]
We are in the phase of implementing final parts related to project and correcting known bugs. We will update all README files of related plugins, probably last week of this month maybe earlier, with installation instruction, how to use them and generally their usage.

However, we do not plan to provide this plugin without based on mongo usage. So, installing mongo will be a requirement.

**Comment by rossjones** [comment]
That's great that documentation is coming, but a shame that there is going to be a hard mongo dependency.. it makes it a lot less re-usable for others running a CKAN.  Nevermind.

Feel free to close this issue.
